Repository zyu22/honeyboard-server, pull requests merged in 2024-12, with the labels that each got.

#21 [feat] SecurityConfig 수정, JwtVerificationFilter 추가, CustomLogoutHandler 추가
  pom.xml
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/auth/model/service/EmailService.java
  src/main/java/com/honeyboard/api/auth/model/service/VerificationService.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/filter/JwtAuthenticationFilter.java
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
  src/main/java/com/honeyboard/api/handler/CustomLogoutHandler.java
  src/main/java/com/honeyboard/api/handler/LoginFailureHandler.java
  src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtService.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/AuthController.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/model/mapper/UserMapper.java
  src/main/java/com/honeyboard/api/user/model/service/CustomOAuth2UserService.java
  src/main/java/com/honeyboard/api/user/model/service/UserService.java
  src/main/java/com/honeyboard/api/user/model/service/UserServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#23 [Setting] 알고리즘 폴더구조 생성
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/java/com/honeyboard/api/algorithm/guide/mapper/AlgorithmGuideMapper.java
  src/main/java/com/honeyboard/api/algorithm/guide/model/AlgorithmGuide.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideService.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/AlgorithmProblem.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolution.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/java/com/honeyboard/api/team/track/controller/TrackTeamController.java
  src/main/java/com/honeyboard/api/team/track/model/TrackTeam.java
  src/main/java/com/honeyboard/api/team/track/service/TrackTeamService.java
Labels: ⚙️ Setting

#24 [feat] 이메일 인증 로직 구현(추후 디테일 수정) 및 디렉토리 구조 변경
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/auth/model/EmailVerification.java
  src/main/java/com/honeyboard/api/auth/model/oauth2/GoogleOAuth2UserInfo.java
  src/main/java/com/honeyboard/api/auth/model/oauth2/KakaoOAuth2UserInfo.java
  src/main/java/com/honeyboard/api/auth/model/oauth2/NaverOAuth2UserInfo.java
  src/main/java/com/honeyboard/api/auth/model/oauth2/OAuth2UserInfo.java
  src/main/java/com/honeyboard/api/auth/model/service/CustomOAuth2UserService.java
  src/main/java/com/honeyboard/api/auth/model/service/EmailServiceImpl.java
  src/main/java/com/honeyboard/api/auth/model/service/VerificationServiceImpl.java
  src/main/java/com/honeyboard/api/auth/model/util/OAuth2UserInfoFactory.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/model/User.java
  src/main/java/com/honeyboard/api/user/model/oauth2/GoogleOAuth2UserInfo.java
  src/main/java/com/honeyboard/api/user/model/oauth2/KakaoOAuth2UserInfo.java
  src/main/java/com/honeyboard/api/user/model/oauth2/NaverOAuth2UserInfo.java
  src/main/java/com/honeyboard/api/user/model/oauth2/OAuth2UserInfo.java
  src/main/java/com/honeyboard/api/user/model/service/CustomOAuth2UserService.java
  src/main/java/com/honeyboard/api/user/model/util/OAuth2UserInfoFactory.java
  src/main/resources/application.properties
Labels: 🚧 Feature

#26 [Setting] 프로젝트 구조 생성
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProject.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/AlgorithmGuideMapper.xml
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: ⚙️ Setting

#30 [feat] AlgorithmProblem, Tag, Pagenation 관련 기능 구현
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/AlgorithmProblem.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java
  src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java
  src/main/java/com/honeyboard/api/algorithm/tag/model/Tag.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
  src/main/java/com/honeyboard/api/common/model/PageInfo.java
  src/main/java/com/honeyboard/api/common/response/PageResponse.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/TagMapper.xml
Labels: 🚧 Feature

#35 [setting] Spring 서버 실행을 위한 설정
  mvnw
  pom.xml
  src/main/java/com/honeyboard/api/HoneyboardApplication.java
  src/main/java/com/honeyboard/api/config/DBConfig.java
  src/main/java/com/honeyboard/api/config/RedisConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/mapper/AlgorithmGuideMapper.xml
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: ⚙️ Setting

#33 [Feat] 알고리즘 문제 풀이 CRUD
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolution.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
Labels: 🚧 Feature

#36 [feat] AWS S3 이미지 관련 기능 개발
  pom.xml
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/common/service/S3/S3Service.java
  src/main/java/com/honeyboard/api/common/service/S3/S3ServiceImp.java
  src/main/java/com/honeyboard/api/config/S3Config.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/honeyboard/api/image/ImageController.java
  src/main/java/com/honeyboard/api/pdf/Document.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java
  src/main/java/com/honeyboard/api/user/model/User.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: 🚧 Feature

#32 [feat] FinaleTeamController 구현
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/auth/model/service/VerificationServiceImpl.java
  src/main/java/com/honeyboard/api/handler/LoginFailureHandler.java
  src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/honeyboard/api/pdf/Document.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleBoardService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/model/CustomUserDetails.java
  src/main/java/com/honeyboard/api/user/model/mapper/UserMapper.java
  src/main/java/com/honeyboard/api/user/model/service/UserService.java
  src/main/java/com/honeyboard/api/user/model/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
  src/main/resources/mapper/FinaleProjectTeamMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#38 [Feat] 관통프로젝트 CRUD API 개발
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProject.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🚧 Feature

#45 [refactor] OAuth2 관련 수정
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🛠️ Refactor

#46 [refactor] 로그인, 이메일 인증 로직 수정
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/auth/model/EmailVerification.java
  src/main/java/com/honeyboard/api/auth/model/service/EmailServiceImpl.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
  src/main/java/com/honeyboard/api/handler/CustomLogoutHandler.java
  src/main/java/com/honeyboard/api/handler/LoginFailureHandler.java
  src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/honeyboard/api/user/model/service/UserDetailsServiceImpl.java
  src/main/java/com/honeyboard/api/util/CookieUtil.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#27 [Feat] 알고리즘 개념 CRUD API 개발 #7
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/java/com/honeyboard/api/algorithm/guide/mapper/AlgorithmGuideMapper.java
  src/main/java/com/honeyboard/api/algorithm/guide/model/AlgorithmGuide.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideService.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideServiceImpl.java
  src/main/resources/mapper/AlgorithmGuideMapper.xml
Labels: 🚧 Feature

#47 [refactor] FinaleProject 관련 로직 수정
  src/main/java/com/honeyboard/api/chat/controller/ChatController.java
  src/main/java/com/honeyboard/api/common/response/FinaleProjectResponse.java
  src/main/java/com/honeyboard/api/config/CurrentUserArgumentResolver.java
  src/main/java/com/honeyboard/api/config/WebConfig.java
  src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java
  src/main/java/com/honeyboard/api/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtService.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/model/CurrentUser.java
  src/main/java/com/honeyboard/api/user/model/User.java
  src/main/java/com/honeyboard/api/user/model/mapper/UserMapper.java
  src/main/java/com/honeyboard/api/user/model/service/UserService.java
  src/main/java/com/honeyboard/api/user/model/service/UserServiceImpl.java
  src/main/java/com/honeyboard/api/util/CookieUtil.java
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/FinaleTeamMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#53 [refactor] UserMapper, UserController, ChatController 수정
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/chat/controller/ChatController.java
  src/main/java/com/honeyboard/api/handler/LoginSuccessHandler.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleMember.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/model/User.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#55 [refactor] User DTO 래퍼클래스 변경, Email UI 변경
  src/main/java/com/honeyboard/api/auth/model/service/EmailServiceImpl.java
  src/main/java/com/honeyboard/api/user/model/User.java
  src/main/resources/application.properties
Labels: ❌ Bug, 🛠️ Refactor, 🎨 Markup

#54 [refactor] WebSocket chatting 버그수정
  src/main/java/com/honeyboard/api/chat/controller/ChatController.java
  src/main/java/com/honeyboard/api/chat/controller/ChatWebSocketController.java
  src/main/java/com/honeyboard/api/chat/mapper/ChatMapper.java
  src/main/java/com/honeyboard/api/chat/service/ChatService.java
  src/main/java/com/honeyboard/api/chat/service/ChatServiceImp.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/config/WebSocketConfig.java
Labels: 🛠️ Refactor

#50 [Feat] 웹 개념, 웹 학습사이트 CRUD API 개발
  src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java
  src/main/java/com/honeyboard/api/web/guide/mapper/WebGuideMapper.java
  src/main/java/com/honeyboard/api/web/guide/model/WebGuide.java
  src/main/java/com/honeyboard/api/web/guide/service/WebGuideService.java
  src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/model/WebRecommend.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/WebGuideMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
Labels: 🚧 Feature

#51 [feat] 관통 게시글 CRUD API 개발
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProjectBoard.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/resources/mapper/TrackProjectBoardMapper.xml
Labels: 🚧 Feature

#56 [feat] 관통 팀 관련 API 개발
  src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackTeamController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackTeamMapper.java
  src/main/java/com/honeyboard/api/project/track/model/TeamMemberInfo.java
  src/main/java/com/honeyboard/api/project/track/model/TeamRole.java
  src/main/java/com/honeyboard/api/project/track/model/TeamStatus.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProjectStatus.java
  src/main/java/com/honeyboard/api/project/track/model/TrackTeam.java
  src/main/java/com/honeyboard/api/project/track/model/TrackTeamMember.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
  src/main/java/com/honeyboard/api/team/track/controller/TrackTeamController.java
  src/main/java/com/honeyboard/api/team/track/model/TrackTeam.java
  src/main/java/com/honeyboard/api/team/track/service/TrackTeamService.java
  src/main/resources/mapper/TrackTeamMapper.xml
  src/test/java/com/honeyboard/api/track/project/controller/TrackControllerTest.java
Labels: 🚧 Feature

#57 [Feat] 일정 CUD 및 캘린더 조회 API 개발 #37
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolution.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/java/com/honeyboard/api/schedule/controller/ScheduleController.java
  src/main/java/com/honeyboard/api/schedule/mapper/ScheduleMapper.java
  src/main/java/com/honeyboard/api/schedule/model/Schedule.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleService.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
Labels: 🚧 Feature

#59 [refactor] 웹 추천 Global Exception 핸들링 적용 및 Mapper 수정
  src/main/java/com/honeyboard/api/project/track/controller/TrackTeamController.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
  src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java
  src/main/java/com/honeyboard/api/web/guide/mapper/WebGuideMapper.java
  src/main/java/com/honeyboard/api/web/guide/service/WebGuideService.java
  src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/WebGuideMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
  src/test/java/com/honeyboard/api/web/guide/controller/WebGuideControllerTest.java
  src/test/java/com/honeyboard/api/web/recommend/controller/WebRecommendControllerTest.java
Labels: 🛠️ Refactor

#58 [feat] 이메일 중복확인 API 추가
  pom.xml
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideServiceImpl.java
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/auth/model/service/VerificationServiceImpl.java
  src/main/java/com/honeyboard/api/chat/controller/ChatController.java
  src/main/java/com/honeyboard/api/chat/service/ChatServiceImp.java
  src/main/java/com/honeyboard/api/config/ThymeleafConfig.java
  src/main/java/com/honeyboard/api/exception/DuplicateEmailException.java
  src/main/java/com/honeyboard/api/exception/InvalidTokenException.java
  src/main/java/com/honeyboard/api/exception/RefreshTokenNotFoundException.java
  src/main/java/com/honeyboard/api/exception/TokenExpiredException.java
  src/main/java/com/honeyboard/api/exception/VerificationCodeException.java
  src/main/java/com/honeyboard/api/exception/VerificationCodeExpiredException.java
  src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/honeyboard/api/pdf/Document.java
  src/main/java/com/honeyboard/api/pdf/controller/PdfController.java
  src/main/java/com/honeyboard/api/pdf/model/Document.java
  src/main/java/com/honeyboard/api/pdf/model/DocumentType.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorService.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectResponse.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/model/LogInUserResponse.java
  src/main/java/com/honeyboard/api/user/model/service/UserServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#61 [Feat] 일정 CUD 및 캘린더 조회 API 개발
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/schedule/model/Schedule.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/test/java/com/honeyboard/api/algorithm/solution/controller/SolutionControllerTest.java
  src/test/java/com/honeyboard/api/schedule/controller/ScheduleControllerTest.java
Labels: 🚧 Feature

#62 [Feat] 일정 CUD 및 캘린더 조회 API 개발
  src/main/java/com/honeyboard/api/schedule/model/Schedule.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/test/java/com/honeyboard/api/schedule/controller/ScheduleControllerTest.java
Labels: 🛠️ Refactor
