Repository zyu22/honeyboard-server, pull requests merged in 2025-02, with the labels that each got.

#196 [bugfix] 파이널 프로젝트 팀 정보 가져오기
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: ❌ Bug

#197 [bugfix] 파이널 프로젝트 팀 정보 가져오기
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: ❌ Bug

#198 [Feat] 파이널프로젝트 물리적삭제로 변경 및 삭제 시 팀 삭제 기능 추가
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: 🚧 Feature, 🛠️ Refactor

#199 [Refactor] 관통프로젝트 상세보기 시 팀장이 이름 먼저오게 수정
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#200 [Refactor] 요청사항 수정
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/WebRecommendMapper.xml
Labels: 🛠️ Refactor

#201 [Refactor] 관통에서 팀원이 팀장 수정 시 팀장 사라지던 문제 해결
  src/main/java/com/honeyboard/api/project/track/mapper/TrackTeamMapper.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
  src/main/resources/mapper/TrackTeamMapper.xml
Labels: 🛠️ Refactor
