Repository zyu22/honeyboard-server, pull requests merged in 2025-01, with the labels that each got.

#64 [refactor] 팀 안 정해진 유저 가져올 때 id 같이 가져오게 수정
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: 🛠️ Refactor

#66 [refactor] directory 구조 변경
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
  src/main/java/com/honeyboard/api/auth/service/CustomOAuth2UserService.java
  src/main/java/com/honeyboard/api/auth/service/EmailService.java
  src/main/java/com/honeyboard/api/auth/service/EmailServiceImpl.java
  src/main/java/com/honeyboard/api/auth/service/VerificationService.java
  src/main/java/com/honeyboard/api/auth/service/VerificationServiceImpl.java
  src/main/java/com/honeyboard/api/auth/util/OAuth2UserInfoFactory.java
  src/main/java/com/honeyboard/api/chat/controller/ChatWebSocketController.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/mapper/UserMapper.java
  src/main/java/com/honeyboard/api/user/service/UserDetailsServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/UserService.java
  src/main/java/com/honeyboard/api/user/service/UserServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#67 [refactor] 관통 프로젝트 test 코드 추가 및 제외인원 추가하는 mapper 추가
  src/main/java/com/honeyboard/api/generation/controller/GenerationController.java
  src/main/java/com/honeyboard/api/generation/mapper/GenerationMapper.java
  src/main/java/com/honeyboard/api/generation/model/Generation.java
  src/main/java/com/honeyboard/api/generation/service/GenerationService.java
  src/main/java/com/honeyboard/api/generation/service/GenerationServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProject.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java
  src/main/java/com/honeyboard/api/user/service/AdminService.java
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
  src/main/java/com/honeyboard/api/web/guide/model/WebGuide.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/mapper/GenerationMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
  src/main/resources/mapper/WebGuideMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
  src/test/java/com/honeyboard/api/generation/controller/GenerationControllerTest.java
  src/test/java/com/honeyboard/api/project/track/controller/TrackProjectControllerTest.java
  src/test/java/com/honeyboard/api/project/track/controller/TrackTeamControllerTest.java
  src/test/java/com/honeyboard/api/web/guide/controller/WebGuideControllerTest.java
  src/test/java/com/honeyboard/api/web/recommend/controller/WebRecommendControllerTest.java
Labels: 🛠️ Refactor

#68 [feat] 관리자 및 기수 API 개발
  src/main/java/com/honeyboard/api/generation/controller/GenerationController.java
  src/main/java/com/honeyboard/api/generation/service/GenerationService.java
  src/main/java/com/honeyboard/api/generation/service/GenerationServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java
  src/main/java/com/honeyboard/api/user/model/UserInfo.java
  src/main/java/com/honeyboard/api/user/service/AdminService.java
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
  src/main/resources/mapper/AdminMapper.xml
  src/test/java/com/honeyboard/api/admin/controller/AdminControllerTest.java
  src/test/java/com/honeyboard/api/generation/controller/GenerationControllerTest.java
Labels: 🚧 Feature

#69 [refactor] DB와 DTO 변수명 안맞는것 통일
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/mapper/WebGuideMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
Labels: 🛠️ Refactor

#60 [Refactor] 커스텀어노테이션 변경
  pom.xml
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideService.java
  src/main/resources/application.properties
  src/main/resources/mapper/AlgorithmGuideMapper.xml
Labels: 🛠️ Refactor

#71 [refactor] finaleTeam 오타 수정 및 테스트 추가
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/web/guide/mapper/WebGuideMapper.java
  src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/FinaleTeamMapper.xml
  src/main/resources/mapper/WebGuideMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
  src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
Labels: 🛠️ Refactor

#70 [refactor] UserName dto 생성, remained user 전달 시 사용
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/model/UserName.java
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: 🛠️ Refactor

#72 [refactor] properties 추가 및 lombok 풀리던 문제 해결
  .gitignore
  .idea/compiler.xml
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/resources/application.properties
  src/main/resources/mapper/AdminMapper.xml
  src/test/java/com/honeyboard/api/admin/controller/AdminControllerTest.java
Labels: ⚙️ Setting

#63 [Feat] 마이페이지 API 기능 구현
  .gitattributes
  .gitignore
  .idea/compiler.xml
  src/main/java/com/honeyboard/api/HoneyboardApplication.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolution.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/mapper/BookmarkMapper.java
  src/main/java/com/honeyboard/api/user/mapper/MyPageMapper.java
  src/main/java/com/honeyboard/api/user/model/Bookmark.java
  src/main/java/com/honeyboard/api/user/model/BookmarksResponse.java
  src/main/java/com/honeyboard/api/user/model/MyAlgorithmSolution.java
  src/main/java/com/honeyboard/api/user/model/MyFinaleProject.java
  src/main/java/com/honeyboard/api/user/model/MyTrackProject.java
  src/main/java/com/honeyboard/api/user/model/User.java
  src/main/java/com/honeyboard/api/user/service/BookmarkService.java
  src/main/java/com/honeyboard/api/user/service/BookmarkServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/MyPageService.java
  src/main/java/com/honeyboard/api/user/service/MyPageServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/MyProjectService.java
  src/main/resources/mapper/BookmarkMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: 🚧 Feature

#77 [refactor] ADMIN 쿼리 결과 반환
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/user/service/AdminService.java
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
Labels: 🛠️ Refactor

#79 [refactor] algorithmGuide 썸네일 추가로 mapper 및 model 수정, .gitignor 수정
  .gitignore
  src/main/java/com/honeyboard/api/algorithm/guide/model/AlgorithmGuide.java
  src/main/resources/mapper/AlgorithmGuideMapper.xml
Labels: 🛠️ Refactor

#80 [refactor] .gitignore 에서 idea 설정 못넣게 추가
  .gitignore
Labels: 🛠️ Refactor

#76 [refactor] FinaleTeam 및 FinaleProject 관련 수정
  .idea/compiler.xml
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/exception/DuplicateTeamMemberException.java
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
  src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleMember.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeamRequest.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/resources/mapper/FinaleTeamMapper.xml
  src/main/resources/mapper/TrackProjectBoardMapper.xml
Labels: 🛠️ Refactor

#81 [Refactor] AlgorithmSolution sql쿼리 수정
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
Labels: 🛠️ Refactor

#82 [refactor] 썸네일 추가로 Project들 mapper 및 model 수정
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProject.java
  src/main/java/com/honeyboard/api/project/track/model/TrackProjectBoard.java
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/TrackProjectBoardMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#83 [refactor] AlgorithmGuideController 수정
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: 🛠️ Refactor

#85 [refactor] BookMark delete 로직변경,북마크+마이페이지 dto 조정
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/mapper/BookmarkMapper.java
  src/main/java/com/honeyboard/api/user/mapper/MyPageMapper.java
  src/main/java/com/honeyboard/api/user/model/bookmark/Bookmark.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedAlgorithmGuide.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedAlgorithmSolution.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedWebGuide.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedWebRecommendation.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarksResponse.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyAlgorithmSolution.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyFinaleProject.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProject.java
  src/main/java/com/honeyboard/api/user/service/BookmarkService.java
  src/main/java/com/honeyboard/api/user/service/BookmarkServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/MyPageService.java
  src/main/java/com/honeyboard/api/user/service/MyPageServiceImpl.java
  src/main/resources/mapper/BookmarkMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: 🛠️ Refactor

#84 [Refactor] 유튜브영상상저장 에러핸들러 추가
  src/main/java/com/honeyboard/api/algorithm/language/controller/ProgrammingLanguageController.java
  src/main/java/com/honeyboard/api/algorithm/language/mapper/ProgrammingLanguageMapper.java
  src/main/java/com/honeyboard/api/algorithm/language/model/ProgrammingLanguage.java
  src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageService.java
  src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageServiceImpl.java
  src/main/java/com/honeyboard/api/exception/DuplicateVideoException.java
  src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java
  src/main/java/com/honeyboard/api/youtube/service/YoutubeServiceImpl.java
  src/main/resources/mapper/ProgrammingLanguageMapper.xml
Labels: 🛠️ Refactor

#87 [docs] Swagger 설정 추가
  .idea/compiler.xml
  pom.xml
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/config/SwaggerConfig.java
  src/main/java/com/honeyboard/api/config/WebConfig.java
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorServiceImpl.java
  src/main/resources/application.properties
Labels: 📑 Docs

#86 [feat] 관통 팀 남은인원 조회 API 추가
  src/main/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideController.java
  src/main/java/com/honeyboard/api/algorithm/guide/mapper/AlgorithmGuideMapper.java
  src/main/java/com/honeyboard/api/algorithm/guide/model/AlgorithmGuide.java
  src/main/java/com/honeyboard/api/algorithm/guide/model/request/AlgorithmGuideRequest.java
  src/main/java/com/honeyboard/api/algorithm/guide/model/response/AlgorithmGuideDetail.java
  src/main/java/com/honeyboard/api/algorithm/guide/model/response/AlgorithmGuideList.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideService.java
  src/main/java/com/honeyboard/api/algorithm/guide/service/AlgorithmGuideServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/request/AlgorithmProblemRequest.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemDetail.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemList.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolutionResponse.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionList.java
  src/main/java/com/honeyboard/api/common/model/CreateResponse.java
  src/main/java/com/honeyboard/api/common/model/PageInfo.java
  src/main/java/com/honeyboard/api/common/response/PageResponse.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackTeamController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackTeamMapper.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/model/bookmark/Bookmark.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedAlgorithmGuide.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedAlgorithmSolution.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarksResponse.java
  src/main/java/com/honeyboard/api/user/service/BookmarkServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/MyPageServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/AlgorithmGuideMapper.xml
  src/main/resources/mapper/TrackTeamMapper.xml
  src/test/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideControllerTest.java
  src/test/java/com/honeyboard/api/config/TestConfig.java
  src/test/java/com/honeyboard/api/project/track/controller/TrackTeamControllerTest.java
  src/test/java/com/honeyboard/api/user/controller/UserControllerTest.java
  src/test/java/com/honeyboard/api/user/controller/UserControllerUnitTest.java
Labels: 🚧 Feature

#88 [refactor] rtr 방식 수정
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
Labels: 🛠️ Refactor

#102 [refactor] 예외 처리 구조 개선
  src/main/java/com/honeyboard/api/auth/service/VerificationServiceImpl.java
  src/main/java/com/honeyboard/api/exception/BusinessException.java
  src/main/java/com/honeyboard/api/exception/DuplicateEmailException.java
  src/main/java/com/honeyboard/api/exception/DuplicateTeamMemberException.java
  src/main/java/com/honeyboard/api/exception/DuplicateVideoException.java
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/exception/InvalidTokenException.java
  src/main/java/com/honeyboard/api/exception/RefreshTokenNotFoundException.java
  src/main/java/com/honeyboard/api/exception/TokenExpiredException.java
  src/main/java/com/honeyboard/api/exception/VerificationCodeException.java
  src/main/java/com/honeyboard/api/exception/VerificationCodeExpiredException.java
  src/main/java/com/honeyboard/api/handler/GlobalExceptionHandler.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/UserServiceImpl.java
  src/main/java/com/honeyboard/api/youtube/service/YoutubeServiceImpl.java
Labels: 🛠️ Refactor

#103 [refactor] Finale 프로젝트 DTO 재구현
  src/main/java/com/honeyboard/api/pdf/controller/PdfController.java
  src/main/java/com/honeyboard/api/pdf/model/Document.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleMember.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProject.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoardDetail.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoardList.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoardRequest.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectCreate.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectDetail.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectList.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectResponse.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectTeamUpdate.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectUpdate.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeam.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeamList.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleTeamRequest.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/project/model/ProjectUserInfo.java
  src/main/java/com/honeyboard/api/project/model/TeamMemberInfo.java
  src/main/java/com/honeyboard/api/project/model/TeamRequest.java
Labels: 🛠️ Refactor

#104 [refactor] package 구조 수정, 컨트롤러 및 서비스 주석처리
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectBoardRequest.java
  src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectCreate.java
  src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectTeamUpdate.java
  src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectUpdate.java
  src/main/java/com/honeyboard/api/project/finale/model/response/FinaleProjectBoardDetail.java
  src/main/java/com/honeyboard/api/project/finale/model/response/FinaleProjectBoardList.java
  src/main/java/com/honeyboard/api/project/finale/model/response/FinaleProjectDetail.java
  src/main/java/com/honeyboard/api/project/finale/model/response/FinaleProjectList.java
  src/main/java/com/honeyboard/api/project/finale/model/response/FinaleTeamList.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
Labels: 🛠️ Refactor

#105 [refactor] 북마크 DTO 추가
  pom.xml
  src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java
  src/main/java/com/honeyboard/api/bookmark/mapper/BookmarkMapper.java
  src/main/java/com/honeyboard/api/bookmark/model/BookmarkResponse.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkService.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/honeyboard/api/pdf/controller/PdfController.java
  src/main/java/com/honeyboard/api/pdf/model/Document.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorService.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectCreate.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/mapper/BookmarkMapper2.java
  src/main/java/com/honeyboard/api/user/service/BookmarkService2.java
  src/main/java/com/honeyboard/api/user/service/BookmarkServiceImpl2.java
  src/main/resources/mapper/BookmarkMapper.xml
  src/test/java/com/honeyboard/api/algorithm/guide/controller/AlgorithmGuideControllerTest.java
  src/test/java/com/honeyboard/api/config/TestConfig.java
  src/test/java/com/honeyboard/api/user/controller/UserControllerUnitTest.java
Labels: 🛠️ Refactor

#106 [refactor] 웹 추천 및 기수 DTO 리팩토링
  src/main/java/com/honeyboard/api/bookmark/mapper/BookmarkMapper.java
  src/main/java/com/honeyboard/api/generation/controller/GenerationController.java
  src/main/java/com/honeyboard/api/generation/mapper/GenerationMapper.java
  src/main/java/com/honeyboard/api/generation/model/GenerationList.java
  src/main/java/com/honeyboard/api/generation/service/GenerationService.java
  src/main/java/com/honeyboard/api/generation/service/GenerationServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java
  src/main/java/com/honeyboard/api/user/service/AdminService.java
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/model/request/WebRecommendRequest.java
  src/main/java/com/honeyboard/api/web/recommend/model/response/WebRecommendDetail.java
  src/main/java/com/honeyboard/api/web/recommend/model/response/WebRecommendList.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/BookmarkMapper.xml
  src/test/java/com/honeyboard/api/admin/controller/AdminControllerTest.java
  src/test/java/com/honeyboard/api/generation/controller/GenerationControllerTest.java
  src/test/java/com/honeyboard/api/web/recommend/controller/WebRecommendControllerTest.java
Labels: 🛠️ Refactor

#107 [Refactor] 알고리즘 문제, 풀이, 태그 DTO 리팩토링
  src/main/java/com/honeyboard/api/algorithm/language/model/ProgrammingLanguage.java
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/AlgorithmProblem.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/request/AlgorithmProblemRequest.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemDetail.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemList.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolution.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/AlgorithmSolutionResponse.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/request/AlgorithmSolutionRequest.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionDetail.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionList.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/tag/model/response/TagResponse.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/ProgrammingLanguageMapper.xml
Labels: 🛠️ Refactor

#109 [Refactor] Algorithm Solution, Tag 주석처리
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionDetail.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java
  src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/TagMapper.xml
Labels: 🛠️ Refactor

#113 [refactor] reset-password api 유저Id 받아오는 로직 추가
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
Labels: 🛠️ Refactor

#114 [refactor] reset-password password encoding 로직 추가
  src/main/java/com/honeyboard/api/user/controller/UserController.java
Labels: 🛠️ Refactor

#115 [refactor] 프로그래밍언어 모델명 수정, Chat 컨벤션 맞추기
  src/main/java/com/honeyboard/api/algorithm/language/controller/ProgrammingLanguageController.java
  src/main/java/com/honeyboard/api/algorithm/language/mapper/ProgrammingLanguageMapper.java
  src/main/java/com/honeyboard/api/algorithm/language/model/LanguageList.java
  src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageService.java
  src/main/java/com/honeyboard/api/algorithm/language/service/ProgrammingLanguageServiceImpl.java
  src/main/java/com/honeyboard/api/chat/controller/ChatController.java
  src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
Labels: 🛠️ Refactor

#116 [refactor] ProgrammingLanguageMapper 수정
  src/main/resources/mapper/ProgrammingLanguageMapper.xml
Labels: 🛠️ Refactor

#121 [Refactor] 웹 추천 중복 추가
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/model/request/TrackProjectBoardRequest.java
  src/main/java/com/honeyboard/api/project/track/model/request/TrackProjectRequest.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/model/request/WebRecommendRequest.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/TrackProjectBoardMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
Labels: 🛠️ Refactor

#122 [refactor] 관통게시글 Url 수정
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
Labels: 🛠️ Refactor

#123 [Refactor] Algorithm Problem, Algorithm Solution, Tag 수정
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/request/AlgorithmProblemRequest.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemDetail.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemList.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionDetail.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java
  src/main/java/com/honeyboard/api/algorithm/tag/model/response/TagResponse.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/TagMapper.xml
Labels: 🛠️ Refactor

#125 [refactor] FinaleProjectBoard 작성 로직 수정
  src/main/java/com/honeyboard/api/config/RedisConfig.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
  src/main/java/com/honeyboard/api/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/honeyboard/api/pdf/controller/PdfController.java
  src/main/java/com/honeyboard/api/pdf/model/Document.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorService.java
  src/main/java/com/honeyboard/api/pdf/service/PdfGeneratorServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/FinaleProjectBoard.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectBoardDetailWithTeam.java
  src/main/resources/application-prod.properties
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
  src/main/resources/templates/pdf/document-template.html
  src/main/resources/templates/pdf/multiple-documents-template.html
Labels: 🛠️ Refactor

#124 [refactor] 관통프로젝트 에러처리 커스텀으로 변경
  src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java
  src/main/java/com/honeyboard/api/bookmark/model/BookmarkListResponse.java
  src/main/java/com/honeyboard/api/bookmark/model/ContentType.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
Labels: 🛠️ Refactor

#127 [refactor] 파이널프로젝트 전체조회시 멤버 한명만 나오는 문제 수정
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/test/java/com/honeyboard/api/project/finale/controller/FinaleProjectControllerTest.java
  src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
Labels: 🛠️ Refactor

#128 [refactor] 피날레프로젝트 id 빼먹은거 수정
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: 🛠️ Refactor

#129 [refactor] 파이널프로젝트 팀 조회 시 하나만 나오던거 수정,
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/response/FinaleTeamList.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: 🛠️ Refactor

#130 [Refactor] Youtube 리팩토링
  src/main/java/com/honeyboard/api/youtube/controller/YoutubeController.java
  src/main/java/com/honeyboard/api/youtube/mapper/YoutubeMapper.java
  src/main/java/com/honeyboard/api/youtube/model/YoutubeSearchResult.java
  src/main/java/com/honeyboard/api/youtube/model/request/YoutubeCreate.java
  src/main/java/com/honeyboard/api/youtube/model/response/YoutubeList.java
  src/main/java/com/honeyboard/api/youtube/model/response/YoutubeResponse.java
  src/main/java/com/honeyboard/api/youtube/service/YoutubeService.java
  src/main/java/com/honeyboard/api/youtube/service/YoutubeServiceImpl.java
  src/main/resources/mapper/YoutubeMapper.xml
Labels: 🛠️ Refactor

#131 [refactor] 리프레쉬토큰을 이용한 액세스토큰 재발급 로직 수정
  pom.xml
  src/main/java/com/honeyboard/api/config/RedisConfig.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/filter/JwtVerificationFilter.java
  src/main/resources/application-dev.properties
Labels: 🛠️ Refactor

#132 [Refactor] schedule 수정
  src/main/java/com/honeyboard/api/schedule/controller/ScheduleController.java
  src/main/java/com/honeyboard/api/schedule/mapper/ScheduleMapper.java
  src/main/java/com/honeyboard/api/schedule/model/Schedule.java
  src/main/java/com/honeyboard/api/schedule/model/request/SceduleRequest.java
  src/main/java/com/honeyboard/api/schedule/model/response/ScheduleList.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleService.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/test/java/com/honeyboard/api/schedule/controller/ScheduleControllerTest.java
Labels: 🛠️ Refactor

#133 [Fix] AlgorithmSolution 페이지네이션 수정
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
Labels: 🛠️ Refactor

#134 [refactor] 북마크 API 수정 및 MyPage 수정
  src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java
  src/main/java/com/honeyboard/api/bookmark/mapper/BookmarkMapper.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkService.java
  src/main/java/com/honeyboard/api/project/model/ProjectUserInfo.java
  src/main/java/com/honeyboard/api/project/model/TeamMemberInfo.java
  src/main/java/com/honeyboard/api/project/model/TeamRequest.java
  src/main/java/com/honeyboard/api/user/controller/UserController.java
  src/main/java/com/honeyboard/api/user/mapper/MyPageMapper.java
  src/main/java/com/honeyboard/api/user/model/bookmark/Bookmark.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedAlgorithmGuide.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedAlgorithmSolution.java
  src/main/java/com/honeyboard/api/user/model/bookmark/BookmarkedWebRecommendation.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyAlgorithmSolutionList.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyFinaleProject.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyFinaleProjectList.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProject.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProjectList.java
  src/main/java/com/honeyboard/api/user/service/MyPageService.java
  src/main/java/com/honeyboard/api/user/service/MyPageServiceImpl.java
  src/main/resources/mapper/BookmarkMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
  src/test/java/com/honeyboard/api/user/controller/UserControllerTest.java
Labels: 🛠️ Refactor

#135 [refactor] HikariCP 설정 추가
  src/main/resources/application-dev.properties
Labels: 🛠️ Refactor

#136 [refactor] 관통 프로젝트 상세조회 팀 이름 안나오던거 수정
  src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectBoardDetail.java
  src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectBoardList.java
  src/main/resources/mapper/TrackProjectBoardMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#137 [refactor] 실행 안되던거 수정
  src/main/resources/mapper/TrackProjectBoardMapper.xml
Labels: 🛠️ Refactor

#138 [Refactor] 웹 개념, 추천 에서 오타, 소문자 수정
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/WebGuideMapper.xml
Labels: 🛠️ Refactor

#140 [Refactor] 웹 개념 생성된 게시글 반환 안되던거 수정
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/web/guide/model/request/WebGuideRequest.java
  src/main/java/com/honeyboard/api/web/guide/service/WebGuideServiceImpl.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/WebGuideMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
  src/test/java/com/honeyboard/api/web/guide/controller/WebGuideControllerTest.java
Labels: 🛠️ Refactor

#141 [Refactor] 오타 수정
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectBoardController.java
  src/main/resources/mapper/WebGuideMapper.xml
Labels: 🛠️ Refactor

#142 [Refactor] Tag 수정
  src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java
  src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
  src/main/resources/mapper/TagMapper.xml
Labels: 🛠️ Refactor

#143 [refactor] TrackProject 생성 관리자권한 추가
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
Labels: 🛠️ Refactor

#144 [Refactor] 웹 개념 검색 수정
  src/main/resources/mapper/AlgorithmGuideMapper.xml
Labels: 🛠️ Refactor

#145 [Refactor] properties prod로 변경, 웹개념 CUD 관리자만 할 수 있게 변경
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/web/guide/controller/WebGuideController.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: 🛠️ Refactor

#146 [Refactor] Tag 검색 추가, AlgorithmProblem 검색 문제 수정
  src/main/java/com/honeyboard/api/algorithm/tag/controller/TagController.java
  src/main/java/com/honeyboard/api/algorithm/tag/mapper/TagMapper.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagService.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/TagMapper.xml
Labels: 🛠️ Refactor

#148 [docs] CICD를 위한 main.yml 파일 생성
  .github/workflows/main.yml
Labels: 🌎 Deploy, 📑 Docs

#151 [Refactor] 배포위한 main.yml 수정
  .github/workflows/main.yml
Labels: 🌎 Deploy, 📑 Docs

#153 [docs] Dockerfile 작성
  Dockerfile
Labels: 📑 Docs

#155 [docs] main.yml 수정
  .github/workflows/main.yml
Labels: 🌎 Deploy, 📑 Docs

#157 [Docs] properies prod로 변경
  src/main/resources/application.properties
Labels: 📑 Docs, 🛠️ Refactor

#158 [refactor] 이메일 인증메일 발송 api verification 수정
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
Labels: ❌ Bug

#159 [Deploy] properties 변경 / 이메일 인증 api 변경
  src/main/resources/application-prod.properties
Labels: 📑 Docs

#161 [Refactor] tag 검색 null 반환으로 수정
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
Labels: 🛠️ Refactor

#162 [Refactor] 마이페이지 프로젝트 쿼리 수정 및 트랙프로젝트 상세조회 삭제된 글 안나오게 수정
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#163 [Refactor] SecurityConfig 수정(관리자), 트랙프로젝트 생성 시 팀 제출현황 조회 되게 변경
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectDetail.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/user/service/MyProjectService.java
  src/main/resources/mapper/TrackProjectBoardMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#164 [Refactor] 관통프로젝트 관련 수정
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProjectList.java
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#166 [refactor] 피날레 프로젝트 로직 수정
  .idea/compiler.xml
  lombok.jar
  lombok.jarZone.Identifier
  mvnw
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
Labels: 🛠️ Refactor

#168 [Refactor] MyTrackProjectList에 boardId, trackTeamId, trackProjectId 추가
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProjectList.java
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🛠️ Refactor

#169 [Feat] TimeZone 설정 추가
  src/main/java/com/honeyboard/api/HoneyboardApplication.java
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🚧 Feature, 🛠️ Refactor

#170 [Deploy] 배포
  .idea/compiler.xml
  lombok.jar
  lombok.jarZone.Identifier
  mvnw
  src/main/java/com/honeyboard/api/HoneyboardApplication.java
  src/main/java/com/honeyboard/api/algorithm/tag/service/TagServiceImp.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectBoardMapper.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/model/response/TrackProjectDetail.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/java/com/honeyboard/api/user/controller/AdminController.java
  src/main/java/com/honeyboard/api/user/mapper/AdminMapper.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyTrackProjectList.java
  src/main/java/com/honeyboard/api/user/service/AdminServiceimpl.java
  src/main/java/com/honeyboard/api/user/service/MyProjectService.java
  src/main/resources/mapper/AdminMapper.xml
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mapper/TrackProjectBoardMapper.xml
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🌎 Deploy

#167 [refactor] delete API에 관리자도 수정 가능하게 수정
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
Labels: 🛠️ Refactor

#171 [Refactor] 요구사항 수정
  src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkService.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/honeyboard/api/user/mapper/MyPageMapper.java
  src/main/resources/mapper/FinaleTeamMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: 🛠️ Refactor

#172 [refactor] 북마크 반환 변수명 수정
  src/main/java/com/honeyboard/api/bookmark/controller/BookmarkController.java
  src/main/java/com/honeyboard/api/bookmark/model/BookmarkListResponse.java
  src/main/java/com/honeyboard/api/bookmark/service/BookmarkServiceImpl.java
Labels: 🛠️ Refactor

#174 [Refactor] 요구사항 수정
  src/main/java/com/honeyboard/api/user/model/mypage/MyAlgorithmSolutionList.java
  src/main/resources/mapper/BookmarkMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: 🛠️ Refactor

#175 [Bugfix] 파이널 보드 삭제된 것 안 가져오게 수정
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectBoardServiceImpl.java
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
Labels: ❌ Bug

#176 [Bugfix] 삭제 안 된걸 가져오게 수정
  src/main/resources/mapper/FinaleProjectBoardMapper.xml
Labels: ❌ Bug

#177 [Bugfix] 관리자 유저 조회 시 기수역순, 이름순 정렬으로 수정
  src/main/resources/mapper/AdminMapper.xml
Labels: ❌ Bug

#178 [Refactor] 알고리즘 문제, 풀이 권한 수정, 에러 메세지 수정
  src/main/java/com/honeyboard/api/algorithm/problem/controller/AlgorithmProblemController.java
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemService.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/java/com/honeyboard/api/algorithm/solution/controller/AlgorithmSolutionController.java
  src/main/java/com/honeyboard/api/algorithm/solution/mapper/AlgorithmSolutionMapper.java
  src/main/java/com/honeyboard/api/algorithm/solution/model/response/AlgorithmSolutionDetail.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionService.java
  src/main/java/com/honeyboard/api/algorithm/solution/service/AlgorithmSolutionServiceImpl.java
  src/main/java/com/honeyboard/api/config/SecurityConfig.java
  src/main/java/com/honeyboard/api/exception/ErrorCode.java
  src/main/java/com/honeyboard/api/schedule/controller/ScheduleController.java
  src/main/java/com/honeyboard/api/schedule/mapper/ScheduleMapper.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleService.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
Labels: 🛠️ Refactor

#179 [Feat] 관통 프로젝트 팀 생성 시 팀원이 있거나 제외인원에 있으면 검색 안되는 기능 추가
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/controller/TrackTeamController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackTeamMapper.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackTeamServiceImpl.java
  src/main/java/com/honeyboard/api/user/model/mypage/MyFinaleProjectList.java
  src/main/resources/application-prod.properties
  src/main/resources/mapper/FinaleTeamMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
  src/main/resources/mapper/TrackTeamMapper.xml
Labels: 🚧 Feature, 🛠️ Refactor

#182 [feat] 트랙프로젝트 제외인원 조회 API 구현
  src/main/java/com/honeyboard/api/project/track/controller/TrackProjectController.java
  src/main/java/com/honeyboard/api/project/track/mapper/TrackProjectMapper.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectService.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectServiceImpl.java
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: 🚧 Feature

#181 [Refactor] QA - 웹 추천 및 관통 수정사항 완료
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectBoardController.java
  src/main/java/com/honeyboard/api/project/track/service/TrackProjectBoardServiceImpl.java
  src/main/java/com/honeyboard/api/web/recommend/controller/WebRecommendController.java
  src/main/java/com/honeyboard/api/web/recommend/mapper/WebRecommendMapper.java
  src/main/java/com/honeyboard/api/web/recommend/model/response/WebRecommendDetail.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendService.java
  src/main/java/com/honeyboard/api/web/recommend/service/WebRecommendServiceImpl.java
  src/main/resources/mapper/TrackProjectBoardMapper.xml
  src/main/resources/mapper/WebRecommendMapper.xml
Labels: 🛠️ Refactor

#183 [Refactor] 일정 등록시 id 반환되지 않도록 수정, Track -> TRACK
  src/main/java/com/honeyboard/api/schedule/controller/ScheduleController.java
  src/main/java/com/honeyboard/api/schedule/mapper/ScheduleMapper.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleService.java
  src/main/java/com/honeyboard/api/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/ScheduleMapper.xml
Labels: 🛠️ Refactor

#185 [bugfix]: Mapper 관련해서 오타 나있는 부분 수정
  src/main/resources/mapper/TrackProjectMapper.xml
Labels: ❌ Bug

#184 [Refactor] Algorithm Problem - 기존 문제가 삭제되면 중복 url 허용
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/model/response/AlgorithmProblemDetail.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
  src/main/resources/mapper/AlgorithmSolutionMapper.xml
  src/main/resources/mapper/MyPageMapper.xml
Labels: 🛠️ Refactor

#187 [refactor] 피날레 보드 생성 수정
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleProjectController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleProjectMapper.java
  src/main/java/com/honeyboard/api/project/finale/model/request/FinaleProjectCreate.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleProjectServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/FinaleProjectMapper.xml
  src/test/java/com/honeyboard/api/project/finale/controller/FinaleTeamControllerTest.java
Labels: ❌ Bug

#189 [refactor] 피날레 프로젝트 팀 수정 로직 수정
  src/main/java/com/honeyboard/api/project/finale/controller/FinaleTeamController.java
  src/main/java/com/honeyboard/api/project/finale/mapper/FinaleTeamMapper.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamService.java
  src/main/java/com/honeyboard/api/project/finale/service/FinaleTeamServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/FinaleTeamMapper.xml
Labels: ❌ Bug

#186 [Refactor] Algorithm Problem 문제수정 중복url확인 수정
  src/main/java/com/honeyboard/api/algorithm/problem/mapper/AlgorithmProblemMapper.java
  src/main/java/com/honeyboard/api/algorithm/problem/service/AlgorithmProblemServiceImpl.java
  src/main/resources/mapper/AlgorithmProblemMapper.xml
Labels: 🛠️ Refactor

#190 [feat] Add api for checking existing email
  src/main/java/com/honeyboard/api/auth/controller/AuthController.java
Labels: 🚧 Feature

#193 [Refactor] 명칭 변경으로 테스트에서 에러나던거 수정
  src/test/java/com/honeyboard/api/project/track/TrackProjectIntegrationTest.java
Labels: 🛠️ Refactor

#194 Create hyo_db_ddl.sql
  hyo_db_ddl.sql
Labels: 🚧 Feature
